#!/usr/bin/env node
require('budo').cli(process.argv.slice(2), {
  browserify: {
    transform: [
      ['babelify', {
        global: true,
        only: [
          /(\.\/index.js|node_modules\/noise-protocol|node_modules\/simple-hypercore-protocol|node_modules\/hmac-blake2b)/
        ]
      }]
    ]
  }
})
